zimmernummer = input("Zimmer:")
etage = input("Etage:")
fenster = input("Anzahl Fenster:")
heizungstyp = input("welche Heizung/Heizkörper sind verbaut?:")
farbe = input ("Welche Farbe haben die Wände?:")
bodenbelag = input("welcher Boden ist vorhanden?:")
balkon = input("Balkon vorhanden?:")
moebel = input("Möbel vorhanden?:")
steckdosen = input("Anzahl Steckdosen:")
groeße = input("Grundfläche in m²:")
preis = input("Preis (€):")
verfügbarkeit = input("verfügbar ab:")

print("\n Zusammenfassung der Angaben:")
print("-----------------------------------------")
print(f"Zimmernummer: {zimmernummer}")
print(f"Etage: {etage}")
print(f"Größe: {groeße} m²")
print(f"Fenster: {fenster}")
print(f"Heizung: {heizungstyp}")
print(f"Farbe: {farbe}")
print(f"Boden: {bodenbelag}")
print(f"Balkon: {balkon}")
print(f"Möbel: {moebel}")
print(f"Steckdosen: {steckdosen}")
print(f"Preis: {preis} €")
print(f"Verfügbar ab: {verfügbarkeit}")